---
- hosts: master
  become: yes
  become_user: ansible
  tasks:
    - name: Copy manifest files to master node.
      copy:
        src: ./nginx.yml
        dest: ~/nginx.yml
        owner: ansible


    - name: Applying manifest files
      shell: |
        kubectl apply -f nginx.yml
